name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    name: Build for Mac
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: go build -v .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: enalim.mac
        path: |
          enalim
          bainsley
          creatures
          images
          maps
          Mirza
          Pirata_One
          src
          config.json
          
    - name: Create info file
      run: |
        echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" > info.txt
      
    - name: Update nightly release
      uses: eine/tip@master
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          enalim.mac
          info.txt

  build-win:
    name: Build for Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: enalim.win
        path: |
          enalim.EXE
          bainsley
          creatures
          images
          maps
          Mirza
          Pirata_One
          src
          config.json

    - name: Create info file
      run: |
        echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" > wininfo.txt
      
    - name: Update nightly release
      uses: eine/tip@master
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          enalim.win
          wininfo.txt
